services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8090"]
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_DB_PATH: /data/db.sqlite3
      DJANGO_STATIC_ROOT: /app/ITRexHelper/staticfiles
      DJANGO_MEDIA_ROOT: /app/ITRexHelper/media
    volumes:
      - django_data:/data
      - static_volume:/app/ITRexHelper/staticfiles
      - ./media:/app/ITRexHelper/media
    expose:
      - "8090"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - static_volume:/staticfiles:ro
      - ./media:/media:ro
    depends_on:
      - web

volumes:
  django_data:
  static_volume:
