# Generated by Django 6.0.6 on 2026-06-17 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема заявки')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('contact_info', models.CharField(blank=True, max_length=255, verbose_name='Контактная информация')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'На рассмотрении'), ('WAITING', 'Ожидание клиента'), ('CLOSED', 'Закрыта'), ('REJECTED', 'Отклонена'), ('CANCELED', 'Отменена')], default='NEW', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий')], default='MEDIUM', max_length=10, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('appointment_time', models.DateTimeField(blank=True, null=True, verbose_name='Время приёма в офисе')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/%d/', verbose_name='PDF-договор')),
                ('author', models.ForeignKey(help_text='Клиент, создавший заявку', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Автор (Клиент)')),
                ('executor', models.ForeignKey(blank=True, help_text='Сотрудник, назначенный на заявку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('is_internal', models.BooleanField(default=False, help_text='Если True, то комментарий виден только сотрудникам', verbose_name='Внутренняя заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда изменено')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к изменению')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tickets.ticket', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История статусов',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
