# Generated by Django 6.0.6 on 2026-06-22 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_comment_options_alter_ticket_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('STATUS_CHANGED', 'Изменение статуса'), ('NEW_COMMENT', 'Новый комментарий'), ('TICKET_CREATED', 'Новая заявка'), ('TICKET_ASSIGNED', 'Назначение исполнителя'), ('CHAT_MESSAGE', 'Сообщение в чате'), ('APPOINTMENT', 'Назначено время приёма')], max_length=20, verbose_name='Тип уведомления')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket', verbose_name='Связанная заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
